const express = require('express')
const cors=require('cors')
const app = express()
const port = 3001
app.use(cors())
app.use(express.json())
const db = require('./config/db')
const Users = require('./routes/UsersRoute')
const NewCars = require('./routes/NewCarsRoute')
const UsedCars = require('./routes/UsedCarsRoute')
const Auth = require('./routes/AuthRoute')
const Orders = require('./routes/OrdersRoute')
const Benz = require('./routes/BenzRoute')
const BMW = require('./routes/BMWRoute')
const Honda = require('./routes/HondaRoute')
const Toyota = require('./routes/ToyotaRoute')
const Volkswagen = require('./routes/VolkswagenRoute')
app.get('/', (req, res) => res.status(418).json({ message: "Welcome" }))
app.use('/users',Users)
app.use('/newcars',NewCars)
app.use('/usedcars',UsedCars)
app.use('/auth',Auth)
app.use('/orders', Orders)
app.use('/benzcars', Benz)
app.use('/bmwcars', BMW)
app.use('/hondacars', Honda)
app.use('/toyotacars', Toyota)
app.use('/volkswagencars', Volkswagen)


app.listen(port, (() => console.log(`Listening on ${port}`)))